# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.30.5/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.30.5/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/aaron/Desktop/sdl-game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/aaron/Desktop/sdl-game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.30.5/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aaron/Desktop/sdl-game/CMakeFiles /Users/aaron/Desktop/sdl-game//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aaron/Desktop/sdl-game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SDL_GAME

# Build rule for target.
SDL_GAME: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL_GAME
.PHONY : SDL_GAME

# fast build rule for target.
SDL_GAME/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/build
.PHONY : SDL_GAME/fast

#=============================================================================
# Target rules for targets named sdl_headers_copy

# Build rule for target.
sdl_headers_copy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sdl_headers_copy
.PHONY : sdl_headers_copy

# fast build rule for target.
sdl_headers_copy/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/sdl_headers_copy.dir/build.make _deps/sdl2-build/CMakeFiles/sdl_headers_copy.dir/build
.PHONY : sdl_headers_copy/fast

#=============================================================================
# Target rules for targets named SDL2main

# Build rule for target.
SDL2main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2main
.PHONY : SDL2main

# fast build rule for target.
SDL2main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2main.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2main.dir/build
.PHONY : SDL2main/fast

#=============================================================================
# Target rules for targets named SDL2

# Build rule for target.
SDL2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2
.PHONY : SDL2

# fast build rule for target.
SDL2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2.dir/build
.PHONY : SDL2/fast

#=============================================================================
# Target rules for targets named SDL2-static

# Build rule for target.
SDL2-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2-static
.PHONY : SDL2-static

# fast build rule for target.
SDL2-static/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2-static.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2-static.dir/build
.PHONY : SDL2-static/fast

#=============================================================================
# Target rules for targets named SDL2_test

# Build rule for target.
SDL2_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_test
.PHONY : SDL2_test

# fast build rule for target.
SDL2_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2_test.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2_test.dir/build
.PHONY : SDL2_test/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/uninstall.dir/build.make _deps/sdl2-build/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named SDL2_ttf

# Build rule for target.
SDL2_ttf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_ttf
.PHONY : SDL2_ttf

# fast build rule for target.
SDL2_ttf/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl_ttf-build/CMakeFiles/SDL2_ttf.dir/build.make _deps/sdl_ttf-build/CMakeFiles/SDL2_ttf.dir/build
.PHONY : SDL2_ttf/fast

src/EntityManagement/Entity.o: src/EntityManagement/Entity.cpp.o
.PHONY : src/EntityManagement/Entity.o

# target to build an object file
src/EntityManagement/Entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/EntityManagement/Entity.cpp.o
.PHONY : src/EntityManagement/Entity.cpp.o

src/EntityManagement/Entity.i: src/EntityManagement/Entity.cpp.i
.PHONY : src/EntityManagement/Entity.i

# target to preprocess a source file
src/EntityManagement/Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/EntityManagement/Entity.cpp.i
.PHONY : src/EntityManagement/Entity.cpp.i

src/EntityManagement/Entity.s: src/EntityManagement/Entity.cpp.s
.PHONY : src/EntityManagement/Entity.s

# target to generate assembly for a file
src/EntityManagement/Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/EntityManagement/Entity.cpp.s
.PHONY : src/EntityManagement/Entity.cpp.s

src/EntityManagement/EntityManager.o: src/EntityManagement/EntityManager.cpp.o
.PHONY : src/EntityManagement/EntityManager.o

# target to build an object file
src/EntityManagement/EntityManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/EntityManagement/EntityManager.cpp.o
.PHONY : src/EntityManagement/EntityManager.cpp.o

src/EntityManagement/EntityManager.i: src/EntityManagement/EntityManager.cpp.i
.PHONY : src/EntityManagement/EntityManager.i

# target to preprocess a source file
src/EntityManagement/EntityManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/EntityManagement/EntityManager.cpp.i
.PHONY : src/EntityManagement/EntityManager.cpp.i

src/EntityManagement/EntityManager.s: src/EntityManagement/EntityManager.cpp.s
.PHONY : src/EntityManagement/EntityManager.s

# target to generate assembly for a file
src/EntityManagement/EntityManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/EntityManagement/EntityManager.cpp.s
.PHONY : src/EntityManagement/EntityManager.cpp.s

src/GameEngine/Action.o: src/GameEngine/Action.cpp.o
.PHONY : src/GameEngine/Action.o

# target to build an object file
src/GameEngine/Action.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/GameEngine/Action.cpp.o
.PHONY : src/GameEngine/Action.cpp.o

src/GameEngine/Action.i: src/GameEngine/Action.cpp.i
.PHONY : src/GameEngine/Action.i

# target to preprocess a source file
src/GameEngine/Action.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/GameEngine/Action.cpp.i
.PHONY : src/GameEngine/Action.cpp.i

src/GameEngine/Action.s: src/GameEngine/Action.cpp.s
.PHONY : src/GameEngine/Action.s

# target to generate assembly for a file
src/GameEngine/Action.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/GameEngine/Action.cpp.s
.PHONY : src/GameEngine/Action.cpp.s

src/GameEngine/GameEngine.o: src/GameEngine/GameEngine.cpp.o
.PHONY : src/GameEngine/GameEngine.o

# target to build an object file
src/GameEngine/GameEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/GameEngine/GameEngine.cpp.o
.PHONY : src/GameEngine/GameEngine.cpp.o

src/GameEngine/GameEngine.i: src/GameEngine/GameEngine.cpp.i
.PHONY : src/GameEngine/GameEngine.i

# target to preprocess a source file
src/GameEngine/GameEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/GameEngine/GameEngine.cpp.i
.PHONY : src/GameEngine/GameEngine.cpp.i

src/GameEngine/GameEngine.s: src/GameEngine/GameEngine.cpp.s
.PHONY : src/GameEngine/GameEngine.s

# target to generate assembly for a file
src/GameEngine/GameEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/GameEngine/GameEngine.cpp.s
.PHONY : src/GameEngine/GameEngine.cpp.s

src/GameEngine/MenuScene.o: src/GameEngine/MenuScene.cpp.o
.PHONY : src/GameEngine/MenuScene.o

# target to build an object file
src/GameEngine/MenuScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/GameEngine/MenuScene.cpp.o
.PHONY : src/GameEngine/MenuScene.cpp.o

src/GameEngine/MenuScene.i: src/GameEngine/MenuScene.cpp.i
.PHONY : src/GameEngine/MenuScene.i

# target to preprocess a source file
src/GameEngine/MenuScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/GameEngine/MenuScene.cpp.i
.PHONY : src/GameEngine/MenuScene.cpp.i

src/GameEngine/MenuScene.s: src/GameEngine/MenuScene.cpp.s
.PHONY : src/GameEngine/MenuScene.s

# target to generate assembly for a file
src/GameEngine/MenuScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/GameEngine/MenuScene.cpp.s
.PHONY : src/GameEngine/MenuScene.cpp.s

src/GameScenes/MainScene.o: src/GameScenes/MainScene.cpp.o
.PHONY : src/GameScenes/MainScene.o

# target to build an object file
src/GameScenes/MainScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/GameScenes/MainScene.cpp.o
.PHONY : src/GameScenes/MainScene.cpp.o

src/GameScenes/MainScene.i: src/GameScenes/MainScene.cpp.i
.PHONY : src/GameScenes/MainScene.i

# target to preprocess a source file
src/GameScenes/MainScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/GameScenes/MainScene.cpp.i
.PHONY : src/GameScenes/MainScene.cpp.i

src/GameScenes/MainScene.s: src/GameScenes/MainScene.cpp.s
.PHONY : src/GameScenes/MainScene.s

# target to generate assembly for a file
src/GameScenes/MainScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/GameScenes/MainScene.cpp.s
.PHONY : src/GameScenes/MainScene.cpp.s

src/Helpers/CollisionHelpers.o: src/Helpers/CollisionHelpers.cpp.o
.PHONY : src/Helpers/CollisionHelpers.o

# target to build an object file
src/Helpers/CollisionHelpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/Helpers/CollisionHelpers.cpp.o
.PHONY : src/Helpers/CollisionHelpers.cpp.o

src/Helpers/CollisionHelpers.i: src/Helpers/CollisionHelpers.cpp.i
.PHONY : src/Helpers/CollisionHelpers.i

# target to preprocess a source file
src/Helpers/CollisionHelpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/Helpers/CollisionHelpers.cpp.i
.PHONY : src/Helpers/CollisionHelpers.cpp.i

src/Helpers/CollisionHelpers.s: src/Helpers/CollisionHelpers.cpp.s
.PHONY : src/Helpers/CollisionHelpers.s

# target to generate assembly for a file
src/Helpers/CollisionHelpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/Helpers/CollisionHelpers.cpp.s
.PHONY : src/Helpers/CollisionHelpers.cpp.s

src/Helpers/MathHelpers.o: src/Helpers/MathHelpers.cpp.o
.PHONY : src/Helpers/MathHelpers.o

# target to build an object file
src/Helpers/MathHelpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/Helpers/MathHelpers.cpp.o
.PHONY : src/Helpers/MathHelpers.cpp.o

src/Helpers/MathHelpers.i: src/Helpers/MathHelpers.cpp.i
.PHONY : src/Helpers/MathHelpers.i

# target to preprocess a source file
src/Helpers/MathHelpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/Helpers/MathHelpers.cpp.i
.PHONY : src/Helpers/MathHelpers.cpp.i

src/Helpers/MathHelpers.s: src/Helpers/MathHelpers.cpp.s
.PHONY : src/Helpers/MathHelpers.s

# target to generate assembly for a file
src/Helpers/MathHelpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/Helpers/MathHelpers.cpp.s
.PHONY : src/Helpers/MathHelpers.cpp.s

src/Helpers/MovementHelpers.o: src/Helpers/MovementHelpers.cpp.o
.PHONY : src/Helpers/MovementHelpers.o

# target to build an object file
src/Helpers/MovementHelpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/Helpers/MovementHelpers.cpp.o
.PHONY : src/Helpers/MovementHelpers.cpp.o

src/Helpers/MovementHelpers.i: src/Helpers/MovementHelpers.cpp.i
.PHONY : src/Helpers/MovementHelpers.i

# target to preprocess a source file
src/Helpers/MovementHelpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/Helpers/MovementHelpers.cpp.i
.PHONY : src/Helpers/MovementHelpers.cpp.i

src/Helpers/MovementHelpers.s: src/Helpers/MovementHelpers.cpp.s
.PHONY : src/Helpers/MovementHelpers.s

# target to generate assembly for a file
src/Helpers/MovementHelpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/Helpers/MovementHelpers.cpp.s
.PHONY : src/Helpers/MovementHelpers.cpp.s

src/Helpers/SpawnHelpers.o: src/Helpers/SpawnHelpers.cpp.o
.PHONY : src/Helpers/SpawnHelpers.o

# target to build an object file
src/Helpers/SpawnHelpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/Helpers/SpawnHelpers.cpp.o
.PHONY : src/Helpers/SpawnHelpers.cpp.o

src/Helpers/SpawnHelpers.i: src/Helpers/SpawnHelpers.cpp.i
.PHONY : src/Helpers/SpawnHelpers.i

# target to preprocess a source file
src/Helpers/SpawnHelpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/Helpers/SpawnHelpers.cpp.i
.PHONY : src/Helpers/SpawnHelpers.cpp.i

src/Helpers/SpawnHelpers.s: src/Helpers/SpawnHelpers.cpp.s
.PHONY : src/Helpers/SpawnHelpers.s

# target to generate assembly for a file
src/Helpers/SpawnHelpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/Helpers/SpawnHelpers.cpp.s
.PHONY : src/Helpers/SpawnHelpers.cpp.s

src/Helpers/TextHelpers.o: src/Helpers/TextHelpers.cpp.o
.PHONY : src/Helpers/TextHelpers.o

# target to build an object file
src/Helpers/TextHelpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/Helpers/TextHelpers.cpp.o
.PHONY : src/Helpers/TextHelpers.cpp.o

src/Helpers/TextHelpers.i: src/Helpers/TextHelpers.cpp.i
.PHONY : src/Helpers/TextHelpers.i

# target to preprocess a source file
src/Helpers/TextHelpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/Helpers/TextHelpers.cpp.i
.PHONY : src/Helpers/TextHelpers.cpp.i

src/Helpers/TextHelpers.s: src/Helpers/TextHelpers.cpp.s
.PHONY : src/Helpers/TextHelpers.s

# target to generate assembly for a file
src/Helpers/TextHelpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/Helpers/TextHelpers.cpp.s
.PHONY : src/Helpers/TextHelpers.cpp.s

src/Helpers/Vec2.o: src/Helpers/Vec2.cpp.o
.PHONY : src/Helpers/Vec2.o

# target to build an object file
src/Helpers/Vec2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/Helpers/Vec2.cpp.o
.PHONY : src/Helpers/Vec2.cpp.o

src/Helpers/Vec2.i: src/Helpers/Vec2.cpp.i
.PHONY : src/Helpers/Vec2.i

# target to preprocess a source file
src/Helpers/Vec2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/Helpers/Vec2.cpp.i
.PHONY : src/Helpers/Vec2.cpp.i

src/Helpers/Vec2.s: src/Helpers/Vec2.cpp.s
.PHONY : src/Helpers/Vec2.s

# target to generate assembly for a file
src/Helpers/Vec2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/Helpers/Vec2.cpp.s
.PHONY : src/Helpers/Vec2.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL_GAME.dir/build.make CMakeFiles/SDL_GAME.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sdl_headers_copy"
	@echo "... uninstall"
	@echo "... SDL2"
	@echo "... SDL2-static"
	@echo "... SDL2_test"
	@echo "... SDL2_ttf"
	@echo "... SDL2main"
	@echo "... SDL_GAME"
	@echo "... src/EntityManagement/Entity.o"
	@echo "... src/EntityManagement/Entity.i"
	@echo "... src/EntityManagement/Entity.s"
	@echo "... src/EntityManagement/EntityManager.o"
	@echo "... src/EntityManagement/EntityManager.i"
	@echo "... src/EntityManagement/EntityManager.s"
	@echo "... src/GameEngine/Action.o"
	@echo "... src/GameEngine/Action.i"
	@echo "... src/GameEngine/Action.s"
	@echo "... src/GameEngine/GameEngine.o"
	@echo "... src/GameEngine/GameEngine.i"
	@echo "... src/GameEngine/GameEngine.s"
	@echo "... src/GameEngine/MenuScene.o"
	@echo "... src/GameEngine/MenuScene.i"
	@echo "... src/GameEngine/MenuScene.s"
	@echo "... src/GameScenes/MainScene.o"
	@echo "... src/GameScenes/MainScene.i"
	@echo "... src/GameScenes/MainScene.s"
	@echo "... src/Helpers/CollisionHelpers.o"
	@echo "... src/Helpers/CollisionHelpers.i"
	@echo "... src/Helpers/CollisionHelpers.s"
	@echo "... src/Helpers/MathHelpers.o"
	@echo "... src/Helpers/MathHelpers.i"
	@echo "... src/Helpers/MathHelpers.s"
	@echo "... src/Helpers/MovementHelpers.o"
	@echo "... src/Helpers/MovementHelpers.i"
	@echo "... src/Helpers/MovementHelpers.s"
	@echo "... src/Helpers/SpawnHelpers.o"
	@echo "... src/Helpers/SpawnHelpers.i"
	@echo "... src/Helpers/SpawnHelpers.s"
	@echo "... src/Helpers/TextHelpers.o"
	@echo "... src/Helpers/TextHelpers.i"
	@echo "... src/Helpers/TextHelpers.s"
	@echo "... src/Helpers/Vec2.o"
	@echo "... src/Helpers/Vec2.i"
	@echo "... src/Helpers/Vec2.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

